export const createPatient = async (payload) => {
    const { data, error: insertError } = await supabaseAdmin
      .from('patients')
      .insert(payload)
      .select()
    return { data, insertError }
}

export const maleInfertilityMapping = {
  "Id": "patientDetails",
  "Scheduled Date": "scheduledDate",
  "Date of First Visit": "demographics.firstVisit",
  "Full Name": "demographics.fullName",
  "Age": "demographics.age",
  "Gender": "demographics.sex",
  "Marital Status": "demographics.maritalStatus",
  "Duration of Marriage": "demographics.durationMarriage",
  "Previous Fertility Evaluation / Treatment": "demographics.previousFertility.status",
  "Previous Fertility Details": "demographics.previousFertility.details",
  "Occupation": "demographics.occupation",
  "Education": "demographics.education",
  "Medical History": "demographics.medicalHistory",
  "Medical History Details": "demographics.medicalHistoryDetails",
  "Surgery": "demographics.surgery.status",
  "Surgery Details": "demographics.surgery.details",
  "Congenital": "demographics.congenital.status",
  "Congenital Details": "demographics.congenital.details",
  "Substance Use": "demographics.substance",
  "Substance Use Details": "demographics.substanceDetails",
  "Smoking Status": "demographics.smoking.status",
  "Cigarettes Per Day": "demographics.smoking.cigarettesPerDay",
  "Alcohol Status": "demographics.alcohol.status",
  "Units per Week": "demographics.alcohol.unitsPerWeek",
  "Height": "demographics.bmi.height",
  "Weight": "demographics.bmi.weight",
  "BMI": "demographics.bmi.value",
  "Family History": "history.family",
  "Consanguinity": "history.consanguinity",
  "STD": "history.std.status",
  "STD Details": "history.std.details",
  "Febrile": "history.febrile.status",
  "Febrile Details": "history.febrile.details",
  "Testicular Problem": "history.testicular.status",
  "Testicular Problem Details": "history.testicular.details",
  "Surgery Type": "history.surgery.type",
  "Therapy Type": "history.therapy.type",
  "Therapy Details": "history.therapy.details",
  "Lubricant Type": "history.lubricants.type",
  "Lubricant Use": "history.lubricants.status",
  "Environment": "history.environment",
  "Lifestyle": "history.lifestyle",
  "Duration of Infertility (years)": "history.duration",
  "Frequency of Intercourse (per week)": "history.frequency",
  "Regularity of Intercourse": "history.regularity",
  "Contraception": "history.contraception",
  "Contraception Method": "history.contraceptionMethod",
  "Knowledge of Ovulatory Period": "history.ovulatoryKnowledge",
  "Erectile Dysfunction": "history.erectileDysfunction.status",
  "Erectile Dysfunction Details": "history.erectileDysfunction.details",
  "Ejaculatory Dysfunction": "history.ejaculatoryDysfunction",
  "Congenital Self": "history.congenitalSelf",
  "Chronic Conditions": "history.chronicConditions",
  "Ejaculate Volume": "history.ejaculateVolume",
  "Infection": "semen.pre.infection",
  "Medications": "semen.pre.medications",
  "Medication Details": "semen.pre.medicationDetails",
  "Collected at Lab": "semen.pre.collectedAtLab",
  "Collection Time": "semen.pre.collectionTime",
  "Delivery Time": "semen.pre.deliveryTime",
  "Abstinence Days": "semen.pre.abstinenceDays",
  "Complete Collection": "semen.pre.completeCollection.status",
  "Missing": "semen.pre.completeCollection.missing",
  "Volume": "semen.macro.volume",
  "pH": "semen.macro.ph",
  "Appearance": "semen.macro.appearance",
  "Viscosity": "semen.macro.viscosity",
  "Liquefaction": "semen.macro.liquefaction",
  "Treatment": "semen.macro.treatment",
  "Agglutination": "semen.macro.agglutination",
  "Total Count": "semen.micro.totalCount",
  "Concentration": "semen.micro.concentration",
  "Progressive Motility": "semen.micro.progressive",
  "Total Motile": "semen.micro.totalMotile",
  "Vitality": "semen.micro.vitality",
  "Motility A": "semen.micro.motility.a",
  "Motility B": "semen.micro.motility.b",
  "Motility C": "semen.micro.motility.c",
  "Motility D": "semen.micro.motility.d",
  "Counting Error": "semen.micro.countingError",
  "WBCs": "semen.cells.wbcs",
  "Fructose": "semen.glands.fructose",
  "Zinc": "semen.glands.zinc",
  "Glucosidase": "semen.glands.glucosidase",
  "Begun Time": "semen.timing.begun",
  "Time to Examination": "semen.timing.toExam",
  "Normal Morphology": "semen.morphology.normal",
  "Abnormal Heads": "semen.morphology.abnormalHeads",
  "Abnormal Mid": "semen.morphology.abnormalMid",
  "Abnormal Tails": "semen.morphology.abnormalTails",
  "ERC": "semen.morphology.erc",
  "TZI": "semen.morphology.tzi",
  "General Appearance": "physical.generalAppearance",
  "Secondary Sexual Characteristics": "physical.secondarySex",
  "Penis": "physical.penis",
  "Gynecomastia": "physical.gynecomastia.status",
  "Gynecomastia Side": "physical.gynecomastia.side",
  "Scars": "physical.scars.status",
  "Scar Location": "physical.scars.location",
  "Vas Left": "physical.vas.left",
  "Vas Right": "physical.vas.right",
  "Left Testis Volume": "physical.testes.left.volume",
  "Left Testis Consistency": "physical.testes.left.consistency",
  "Right Testis Volume": "physical.testes.right.volume",
  "Right Testis Consistency": "physical.testes.right.consistency",
  "Epididymis": "physical.epididymis",
  "Spermatic Cord": "physical.spermaticCords.status",
  "Spermatic Cord Grade": "physical.spermaticCords.grade",
  "Rectal Exam": "physical.rectal.status",
  "Rectal Findings": "physical.rectal.findings",
  "FSH": "investigations.fsh.value",
  "LH": "investigations.lh.value",
  "TE": "investigations.te.value",
  "Testosterone": "investigations.testosterone.value",
  "Estradiol": "investigations.estradiol.value",
  "Prolactin": "investigations.prolactin.value",
  "ASA": "investigations.asa.result",
  "Viability": "investigations.viability.result",
  "Sperm Function": "investigations.spermFunction.result",
  "Prostatic Fluid": "investigations.prostaticFluid.result",
  "Semen Culture": "investigations.semenCulture.result",
  "Urine Culture": "investigations.urineCulture.result",
  "USG Findings": "investigations.usg.findings",
  "TRUS Findings": "investigations.trus.findings",
  "Biopsy Histology": "investigations.biopsy.histology",
  "Notes": "final.notes",
  "Approved By": "final.approvedBy"
};

export const maleSexualDysfunctionMapping = {
  "Id": "patientDetails",
  "Scheduled Date": "scheduledDate",
  "Full Name": "demographics.fullName",
  "Date of Birth": "demographics.dateOfBirth",
  "Age (in years)": "demographics.age",
  "Gender": "demographics.gender",
  "Date of First Visit": "demographics.firstVisit",
  "Contact Information": "demographics.contact",
  "Address / Pin code (optional)": "demographics.address",
  "Marital Status": "demographics.maritalStatus",
  "Duration of Marriage (years)": "demographics.durationMarriage",
  "Education Level": "demographics.education",
  "Occupation": "demographics.occupation",
  "Weight": "demographics.weight",
  "Height": "demographics.height",
  "BMI": "demographics.bmi",
  "Diabetes Mellitus": "medical.diabetes.status",
  "Diabetes Comments": "medical.diabetes.comments",
  "Hypertension": "medical.hypertension.status",
  "Hypertension Comments": "medical.hypertension.comments",
  "Thyroid Disorders": "medical.thyroid.status",
  "Thyroid Comments": "medical.thyroid.comments",
  "Cardiovascular Disease": "medical.cardiovascular.status",
  "Cardiovascular Comments": "medical.cardiovascular.comments",
  "Neurological Disorders": "medical.neurological.status",
  "Neurological Comments": "medical.neurological.comments",
  "Psychiatric Conditions": "medical.psychiatric.status",
  "Psychiatric Comments": "medical.psychiatric.comments",
  "Hormonal Disorders": "medical.hormonal.status",
  "Hormonal Comments": "medical.hormonal.comments",
  "History of STIs": "medical.stis.status",
  "STI Type": "medical.stis.type",
  "STI Year": "medical.stis.year",
  "Chronic Kidney Disease": "medical.kidney.status",
  "Kidney Comments": "medical.kidney.comments",
  "Liver Disease": "medical.liver.status",
  "Liver Comments": "medical.liver.comments",
  "Past/Persistent Genital Infections": "medical.genitalInfections.status",
  "Genital Infections Specify": "medical.genitalInfections.specify",
  "Other Chronic Illnesses": "medical.otherChronic.status",
  "Other Chronic Specify": "medical.otherChronic.specify",
  "Varicocele": "surgical.varicocele.status",
  "Varicocele Year": "surgical.varicocele.year",
  "Hernia Repair (Inguinal/Scrotal)": "surgical.hernia.status",
  "Hernia Year": "surgical.hernia.year",
  "Prostate Surgery/TURP": "surgical.prostate.status",
  "Prostate Year": "surgical.prostate.year",
  "Testicular Surgery": "surgical.testicular.status",
  "Testicular Year": "surgical.testicular.year",
  "Pelvic or Genital Trauma": "surgical.trauma.status",
  "Trauma Year": "surgical.trauma.year",
  "Vasectomy": "surgical.vasectomy.status",
  "Vasectomy Year": "surgical.vasectomy.year",
  "Other Urogenital Surgeries": "surgical.otherUrogenital.status",
  "Other Urogenital Specify": "surgical.otherUrogenital.specify",
  "Other Major Surgeries (non-urogenital)": "surgical.otherMajor.status",
  "Other Major Specify": "surgical.otherMajor.specify",
  "Recreational Drug Use": "lifestyle.drugUse.status",
  "Drug Use Substance": "lifestyle.drugUse.substance",
  "Anabolic Steroid Use": "lifestyle.steroids.status",
  "Steroid Duration/Frequency": "lifestyle.steroids.duration",
  "Occupational Exposure to Heat/Radiation": "lifestyle.exposure.status",
  "Exposure Job Role/Type": "lifestyle.exposure.details",
  "Psychological Stress (Persistent/High)": "lifestyle.stress.status",
  "Stress Details": "lifestyle.stress.details",
  "Sleep Disturbances/Disorders": "lifestyle.sleep.status",
  "Sleep Details": "lifestyle.sleep.details",
  "Sedentary Lifestyle": "lifestyle.sedentary.status",
  "Daily Physical Activity": "lifestyle.sedentary.activity",
  "Use of Sexual Enhancement Substances": "lifestyle.enhancement.status",
  "Enhancement Type": "lifestyle.enhancement.type",
  "Pornography Addiction/Excessive Use": "lifestyle.pornography.status",
  "Pornography Frequency or Impact": "lifestyle.pornography.impact",
  "Current erection rigidity (0-100%)": "sexual.currentRigidity",
  "Best achievable rigidity (%)": "sexual.bestRigidity",
  "Duration of erection (minutes)": "sexual.duration",
  "Do you get morning erections?": "sexual.morningErections",
  "Are morning erections better/longer than during intercourse?": "sexual.morningBetter",
  "Date of last morning erection": "sexual.lastMorningErection",
  "Do you get overnight erections?": "sexual.overnightErections",
  "Rigidity of overnight erections (%)": "sexual.overnightRigidity",
  "Does erection lose rigidity during intercourse?": "sexual.losesRigidity",
  "Does it stay erect until immediately after penetration?": "sexual.staysErect",
  "Erection curvature": "sexual.curvature",
  "Numbness or unusual penile sensation?": "sexual.numbness",
  "Numbness Details": "sexual.numbnessDetails",
  "Onset of ED symptoms": "sexual.edOnset",
  "Duration since ED began": "sexual.edDuration",
  "Significant event or medication change at onset?": "sexual.significantEvent",
  "Event Details": "sexual.eventDetails",
  "Last time erection was normal": "sexual.lastNormalErection",
  "Erections better during:": "sexual.betterDuring",
  "Rigidity during masturbation vs intercourse": "sexual.masturbationRigidity",
  "Problem with:": "sexual.problemType",
  "ED progression:": "sexual.progression",
  "Daily variation in erection quality": "sexual.dailyVariation",
  "History of sexual trauma": "sexual.trauma",
  "Trauma Details": "sexual.traumaDetails",
  "Rigidity at the time of ejaculation (%)": "sexual.ejaculationRigidity",
  "Libido Status": "sexual.libido",
  "If ED wasn't a problem, desired intercourse frequency (per week)": "sexual.desiredFrequency",
  "Does your partner know you're seeking treatment?": "sexual.partnerKnows",
  "Is your partner supportive or encouraging?": "sexual.partnerSupportive",
  "Would they be willing to join treatment if needed?": "sexual.partnerWilling",
  "Who usually initiates intercourse?": "sexual.initiates",
  "Current intercourse attempts": "sexual.currentAttempts",
  "Attempts Frequency": "sexual.attemptsFrequency",
  "If untreated, what impact might ED have on your relationship?": "sexual.relationshipImpact",
  "Previous treatments for ED tried?": "sexual.previousTreatments",
  "Treatment Details": "sexual.treatmentDetails",
  "Current contraceptive method used (if any)": "sexual.contraceptive",
  "Other contraceptive method": "sexual.contraceptiveOther",
  "Would patient be satisfied with 65-75% rigidity for 10-15 min?": "sexual.satisfiedWith65",
  "If not, what would be considered a successful treatment outcome?": "sexual.successfulOutcome",
  "Date of Collection": "semen.collectionDate",
  "Abstinence (days)": "semen.abstinence",
  "Sample Status": "semen.sampleStatus",
  "Time to analysis (mins)": "semen.timeToAnalysis",
  "Volume (mL)": "semen.volume",
  "Sperm Concentration (×10⁶/mL)": "semen.concentration",
  "Total motility (%)": "semen.motility",
  "Morphology normal forms (%)": "semen.morphology",
  "pH (optional)": "semen.pH",
  "Liquefication time (mins)": "semen.liquefication",
  "Total Testosterone": "hormonal.testosterone.done",
  "Testosterone Date of Test": "hormonal.testosterone.date",
  "Testosterone Patient Value": "hormonal.testosterone.value",
  "Testosterone Interpretation": "hormonal.testosterone.interpretation",
  "FSH (Follicle Stimulating Hormone)": "hormonal.fsh.done",
  "FSH Date of Test": "hormonal.fsh.date",
  "FSH Patient Value": "hormonal.fsh.value",
  "FSH Interpretation": "hormonal.fsh.interpretation",
  "LH (Luteinizing Hormone)": "hormonal.lh.done",
  "LH Date of Test": "hormonal.lh.date",
  "LH Patient Value": "hormonal.lh.value",
  "LH Interpretation": "hormonal.lh.interpretation",
  "Prolactin": "hormonal.prolactin.done",
  "Prolactin Date of Test": "hormonal.prolactin.date",
  "Prolactin Patient Value": "hormonal.prolactin.value",
  "Prolactin Interpretation": "hormonal.prolactin.interpretation",
  "TSH (Thyroid Stim. Hormone)": "hormonal.tsh.done",
  "TSH Date of Test": "hormonal.tsh.date",
  "TSH Patient Value": "hormonal.tsh.value",
  "TSH Interpretation": "hormonal.tsh.interpretation",
  "Estradiol (if done)": "hormonal.estradiol.done",
  "Estradiol Date of Test": "hormonal.estradiol.date",
  "Estradiol Patient Value": "hormonal.estradiol.value",
  "Estradiol Interpretation": "hormonal.estradiol.interpretation",
  "SHBG (optional)": "hormonal.shbg.done",
  "SHBG Date of Test": "hormonal.shbg.date",
  "SHBG Patient Value": "hormonal.shbg.value",
  "SHBG Interpretation": "hormonal.shbg.interpretation",
  "Erection Hardness Score 1: Penis is larger but not hard": "scoring.ehs.score1",
  "Erection Hardness Score 2: Penis is hard but not hard enough for penetration": "scoring.ehs.score2",
  "Erection Hardness Score 3: Penis is hard enough for penetration but not completely hard": "scoring.ehs.score3",
  "Erection Hardness Score 4: Penis is completely hard and fully rigid": "scoring.ehs.score4",
  "IIEF Q1: How often were you able to get an erection during sexual activity?": "scoring.iief.q1",
  "IIEF Q2: When you had erections with sexual stimulation, how often were your erections hard enough for penetration?": "scoring.iief.q2",
  "IIEF Q3: When you attempted intercourse, how often were you able to penetrate (enter) your partner?": "scoring.iief.q3",
  "IIEF Q4: During sexual intercourse, how often were you able to maintain your erection after you had penetrated (entered) your partner?": "scoring.iief.q4",
  "IIEF Q5: During sexual intercourse, how difficult was it to maintain your erection to completion of intercourse?": "scoring.iief.q5",
  "IIEF Q6: How many times have you attempted sexual intercourse?": "scoring.iief.q6",
  "IIEF Q7: When you attempted sexual intercourse, how often was it satisfactory for you?": "scoring.iief.q7",
  "IIEF Q8: How much have you enjoyed sexual intercourse?": "scoring.iief.q8",
  "IIEF Q9: When you had sexual stimulation or intercourse, how often did you ejaculate?": "scoring.iief.q9",
  "IIEF Q10: When you had sexual stimulation or intercourse, how often did you have the feeling of orgasm or climax?": "scoring.iief.q10",
  "IIEF Q11: How often have you felt sexual desire?": "scoring.iief.q11",
  "IIEF Q12: How would you rate your level of sexual desire?": "scoring.iief.q12",
  "IIEF Q13: How satisfied have you been with your overall sex life?": "scoring.iief.q13",
  "IIEF Q14: How satisfied have you been with your sexual relationship with your partner?": "scoring.iief.q14",
  "IIEF Q15: How do you rate your confidence that you could get and keep an erection?": "scoring.iief.q15",
  "Scrotal Ultrasound": "imaging.scrotalUltrasound.done",
  "Scrotal Ultrasound Date": "imaging.scrotalUltrasound.date",
  "Scrotal Ultrasound Findings/Remarks": "imaging.scrotalUltrasound.findings",
  "Penile Doppler (if done)": "imaging.penileDoppler.done",
  "Penile Doppler Date": "imaging.penileDoppler.date",
  "Penile Doppler Findings/Remarks": "imaging.penileDoppler.findings",
  "Other imaging (e.g. MRI, CT)": "imaging.otherImaging.done",
  "Other Imaging Type": "imaging.otherImaging.type",
  "Other Imaging Date": "imaging.otherImaging.date",
  "Other Imaging Findings": "imaging.otherImaging.findings",
  "Urological Exam (if applicable)": "imaging.urologicalExam.done",
  "Urological Exam Date": "imaging.urologicalExam.date",
  "Urological Exam Findings/Remarks": "imaging.urologicalExam.findings",
  "PHQ-9 (Patient Health Questionnaire-9 item scale) Depression screening": "psychological.phq9.score",
  "PHQ-9 Interpretation": "psychological.phq9.interpretation",
  "GAD-7 Score (Generalized Anxiety Disorder-7 Item scale) Anxiety Screening": "psychological.gad7.score",
  "GAD-7 Interpretation": "psychological.gad7.interpretation",
  "Perceived Stress Level": "psychological.stressLevel",
  "Emotional issues related to infertility or ED?": "psychological.emotionalIssues",
  "If yes, specify": "psychological.emotionalIssuesDetails",
  "Referral to mental health professional?": "psychological.referral",
  "Referral Status": "psychological.referralStatus",
  "Next Scheduled Visit": "followup.nextVisit",
  "Lifestyle Modifications Reinforced": "followup.lifestyleModifications",
  "Referral Advised": "followup.referral",
  "Further Investigations Planned": "followup.investigations",
  "Patient Compliance and Motivation": "followup.compliance",
  "General Remarks": "followup.remarks"
};